name: LuaCraftBeta
description: A plugin that integrates Lua scripting into Minecraft.
main: com.shawnjb.luacraftbeta.LuaCraftBetaPlugin
version: 0.1.1
authors:
  - shawnjb
softdepend:
  - Essentials

commands:
  loadscript:
    description: Load a Lua script by name.
    usage: /<command> <scriptName>
    permission: luacraftbeta.loadscript
    permission-message: You do not have permission to use this command.
  
  listscripts:
    description: List all available Lua scripts in the scripts directory.
    usage: /<command>
    permission: luacraftbeta.listscripts
    permission-message: You do not have permission to use this command.

permissions:
  luacraftbeta.*:
    description: Gives access to all LuaCraftBeta commands.
    children:
      luacraftbeta.loadscript: true
      luacraftbeta.listscripts: true
  luacraftbeta.loadscript:
    description: Allows access to the /loadscript command.
  luacraftbeta.listscripts:
    description: Allows access to the /listscripts command.
