name: LuaCraftBeta
description: A plugin that integrates Lua scripting into Minecraft.
main: com.shawndoeswhat.luacraftbeta.LuaCraftBetaPlugin
version: 0.1.7-SNAPSHOT
authors:
  - shawndoeswhat
softdepend:
  - Essentials

commands:
  loadscript:
    description: Load a Lua script by name.
    usage: /<command> <scriptName>
    permission: luacraftbeta.loadscript
    permission-message: You do not have permission to use this command.

  listscripts:
    description: List all available Lua scripts in the scripts directory.
    usage: /<command>
    permission: luacraftbeta.listscripts
    permission-message: You do not have permission to use this command.

  runscript:
    description: Executes inline Lua code (admin only).
    usage: /<command> <lua code>
    permission: luacraftbeta.runscript
    permission-message: You do not have permission to use this command.

  luainfo:
    description: Displays LuaCraftBeta info and statistics.
    usage: /<command>
    permission: luacraftbeta.luainfo
    permission-message: You do not have permission to use this command.

  lcbconsole:
    description: Opens the LuaCraftBeta GUI console.
    usage: /<command>
    permission: luacraftbeta.console
    permission-message: You do not have permission to use this command.

  luaconsole:
    description: Opens the LuaCraftBeta GUI console (alias of /lcbconsole).
    usage: /<command>
    permission: luacraftbeta.console
    permission-message: You do not have permission to use this command.

  resetlua:
    description: Resets the Lua environment.
    usage: /<command>
    permission: luacraftbeta.resetlua
    permission-message: You do not have permission to use this command.

permissions:
  luacraftbeta.*:
    description: Gives access to all LuaCraftBeta commands.
    children:
      luacraftbeta.loadscript: true
      luacraftbeta.listscripts: true
      luacraftbeta.runscript: true
      luacraftbeta.luainfo: true
      luacraftbeta.console: true
      luacraftbeta.resetlua: true

  luacraftbeta.loadscript:
    description: Allows access to the /loadscript command.
  luacraftbeta.listscripts:
    description: Allows access to the /listscripts command.
  luacraftbeta.runscript:
    description: Allows access to the /runscript command.
  luacraftbeta.luainfo:
    description: Allows access to the /luainfo command.
  luacraftbeta.console:
    description: Allows access to /lcbconsole and /luaconsole.
  luacraftbeta.resetlua:
    description: Allows access to the /resetlua command.
